/**
 * @module pulse-weather/fonts
 * @description Auto-generated by scripts/inline-fonts.mjs.
 * Do not edit by hand — re-run "npm run prebuild" instead.
 *
 * Sections inherit the HA system font stack by default, so the
 * default bundle is empty. To inline a custom face, add an entry to
 * scripts/inline-fonts.mjs and re-run "npm run prebuild".
 */

export const FONT_FACES = ``;
