blank_issues_enabled: true
contact_links:
  - name: Questions and help
    url: https://github.com/hiall-fyi/pulse-card/discussions
    about: For usage questions and general help, please use Discussions.
