#!/usr/bin/env node
// Reads DEV/fonts/*.woff2 and emits src/pulse-weather/fonts.js
// containing @font-face declarations with base64-encoded woff2 data.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

// Sections inherit the HA system font stack by default. To inline a
// custom face, push an entry { family, weight, file } and point the
// relevant CSS rule at the family. The woff2 file lives under
// DEV/fonts/ and is base64-embedded into the bundle.
const FONTS = [];

function inlineOne({ family, weight, file }) {
  const path = resolve(root, 'DEV/fonts', file);
  if (!existsSync(path)) {
    throw new Error(`Font file missing: ${path}. Run Task 1 first.`);
  }
  const buf = readFileSync(path);
  const b64 = buf.toString('base64');
  return [
    `@font-face {`,
    `  font-family: '${family}';`,
    `  font-style: normal;`,
    `  font-weight: ${weight};`,
    `  font-display: swap;`,
    `  src: url(data:font/woff2;base64,${b64}) format('woff2');`,
    `}`,
  ].join('\n');
}

const css = FONTS.map(inlineOne).join('\n\n');

const header = `/**
 * @module pulse-weather/fonts
 * @description Auto-generated by scripts/inline-fonts.mjs.
 * Do not edit by hand — re-run "npm run prebuild" instead.
 *
 * Sections inherit the HA system font stack by default, so the
 * default bundle is empty. To inline a custom face, add an entry to
 * scripts/inline-fonts.mjs and re-run "npm run prebuild".
 */

`;

const body = 'export const FONT_FACES = `' + css + '`;\n';

writeFileSync(resolve(root, 'src/pulse-weather/fonts.js'), header + body);
console.log('Wrote src/pulse-weather/fonts.js');
